### ISSUE TITLE
Wow. Can't stop loving this! :)

### ISSUE THREAD

**Issue by xparq** [fragglet/dos-help-files#1]
Thanks a lot, this is so beautiful!
I don't think I can actually use it unfortunately _(albeit, as a matter of fact, I bumped across the NMAKE help via Google, and indeed -- as you said --, most of it is still relevant! :) )_, but I'm barely able to leave those wonderfully converted pages alone...

_(I was a big fan of the MS QuickHelp format, as you can tell.)_

**Comment by fragglet** [comment]
Thank you, it was a silly niche project but your comment makes it all the worthwhile. Microsoft got a lot of well deserved (?) criticism for their software in the 90s but their online documentation truly was top notch.

**Comment by fragglet** [comment]
(By the way, if you're a Microsoft documentation geek, check out the [Works tutorials](https://youtube.com/playlist?list=PLHt4bcu83-6Qxdq0F7XKxgkbsJSlrtwWX) that I recorded some videos of a while back)

**Comment by xparq** [comment]
> By the way, if you're a Microsoft documentation geek, check out the [Works tutorials](https://youtube.com/playlist?list=PLHt4bcu83-6Qxdq0F7XKxgkbsJSlrtwWX) that I recorded some videos of a while back)

Thanks for the hint, I've never actually used Works, but I've had a quick glance of the 1st video, and the ASCII art there is truly astonishing! :-o

**Comment by xparq** [comment]
> Thank you, it was a silly niche project but your comment makes it all the worthwhile. Microsoft got a lot of well deserved (?) criticism for their software in the 90s but their online documentation truly was top notch.

Absolutely. And I loved the MSC6 compiler + libs, too (preferred it to Borland's Turbo C), so it was such a great surprise to see you've archived even that! :) (I remember searching for it earlier online for quite a while in vain (after failing to load it from an old CD). Eventually I've found it somewhere, but it's still unsettling (+ kinda sad) how these things can just disappear for good.)

_(Sorry about polluting your Issue space! :) )_
